fsmi/odie-client

index.html
=> Advertise mailing list

correction.html, js/vm/correction.js, preselection.html, print.html
=> Corrections feedback

css/app.css, js/vm/cart.js, js/vm/printjob.js, views/preselection.html
=> Fixes issues #50, #49, #55

css/app.css, js/ko/formatter.js, js/lib.js, js/main.js, js/vm/cart.js, js/vm/correction.js, js/vm/depositreturn.js, js/vm/log.js, js/vm/printjob.js, package.json, views/cart.html, views/index.html, views/log.html, views/print.html
Fixes #46
http://kha.github.io/odie-client/dist/
=> Add global, summable actions log

js/vm/preselection.js
=> Make preselection filter case insensitive

views/documentselection.html
=> title text for document type icons

js/vm/printjob.js, views/print.html
Implementation of requested feature #48
=> saving a cart is now possible when logged in

js/main.js, js/vm/printjob.js, views/print.html
I like it, Max not so much :)
http://kha.github.io/odie-client/dist/
=> [Diffbase #84] Group 'print' (primary action) and 'save' (secondary action) into split button

js/vm/cart.js, js/vm/preselection.js, js/vm/printjob.js, views/correction.html, views/preselection.html, views/print.html
Makes PrintJob.{,_}coverText redundant.
Supersedes #85.
=> Preselection: Prevent original carts from being modified

js/api.js, js/app.js, js/main.js, js/store.js, js/vm/cart.js, js/vm/correction.js, js/vm/depositreturn.js, js/vm/documentlist.js, js/vm/documentselection.js, js/vm/preselection.js, js/vm/printjob.js, js/vm/user.js, views/cart.html, views/print.html
Delay application start until after store initialization to retain
sanity
=> Load config from server

js/vm/correction.js, views/correction.html
=> Support for Donations

js/vm/cart.js, js/vm/documentlist.js
This reverts commit 7dd4d45bd6635f2987ed247f3da767751d24cd36.
=> Fix Cart.contains not being trackable by knockout

Brocfile.js, js/ko/bootstrap-datepicker.js, js/ko/bootstrap-tagsinput.js, js/main.js, js/typeaheadsource.js, js/vm/documentselection.js, js/vm/documentsubmission.js, less/app.less, package.json, views/documentsubmission.html, views/index.html
TODO: Some explanatory text on the document submission page. Also the submit button should probably be disabled while waiting and after the first success to prevent accidental double submissions.
=> Document submission

js/collection.js, js/vm/documentlist.js, js/vm/documentselection.js, less/app.less, views/documentlist.html, views/documentselection.html, views/documentsubmission.html
https://www-test.fsmi.uni-karlsruhe.de/odie-next/web/#documentselection/l44
Paging @dedrone
=> The death of the toggle of death

views/documentsubmission.html
New lectures containing a comma could otherwise not be entered
=> Disable automatic completion on comma

views/documentlist.html
FS votes:
2x 'okay'
1x 'meh *shrug*'
=> views/documentlist: De-emphasize validationTime

js/vm/transcriptmigration.js
=> Fix doc submission in migration tab

js/vm/documentlist.js
=> documentlist: Fix scrubbed documents mismatch for count and cart add

views/documentsubmission.html
Because let's be honest, who reads the stuff at the top before filling
out the form? I know I didn't when I first saw that form :)
=> documentsubmission: Inline filling-out hints in the form

js/vm/transcriptmigration.js, views/transcriptmigration.html
The date is then set to the first of the month or year, respectively.
=> transcriptmigration: Allow entering dates in YYYY and YYYY-MM format

js/vm/transcriptmigration.js
=> Fix CSRF token header for transcript migration

views/documentsubmission.html
=> Call oral reexams by their old name again

views/documentlist.html
...by completely removing them from the DOM
=> views/documentlist: Fix hidden items affecting button corners

js/ko/formatter.js, js/main.js, js/vm/depositreturn.js, js/vm/documentselection.js, js/vm/documentsubmission.js, less/app.less, views/depositreturn.html, views/documentselection.html, views/documentsubmission.html
Tested this version last week on the testserver. There was no negative feedback, so I am going to deploy it on Monday/Tuesday.
=> Early document reward

js/api.js, js/vm/depositreturn.js, js/vm/log.js, views/depositreturn.html, views/log.html
Due to some error, this is feature is already on the productive env
=> Reject documents

js/vm/documentlist.js, views/documentselection-cart.html, views/documentsubmission.html
Please review (should be pretty painless).
Introduces the client-side document type for mock exams (#186), cf [#160 of odie-server](https://github.com/fsmi/odie-server/pull/160)
=> Introduce mock exam type

js/main.js, js/vm/datenschutz.js, views/datenschutz.html, views/index.html
=> Add Datenschutz info

views/documentlist.html
Accompanying change to https://github.com/fsmi/odie-server/pull/168
=> Add note about whitelisting sortable columns to views/documentlist.html
